import type { position } from "./interfaces";

export function convertChar(type: string): position {
    // Row 0
    if (type === "0big") return { x: 0, y: 0 }
    if (type === "1big") return { x: 1, y: 0 }
    if (type === "2big") return { x: 2, y: 0 }
    if (type === "3big") return { x: 3, y: 0 }
    if (type === "4big") return { x: 4, y: 0 }
    if (type === "5big") return { x: 5, y: 0 }
    if (type === "6big") return { x: 6, y: 0 }
    if (type === "7big") return { x: 7, y: 0 }
    if (type === "8big") return { x: 8, y: 0 }
    if (type === "9big") return { x: 9, y: 0 }
    if (type === "+") return { x: 10, y: 0 }
    if (type === "-") return { x: 11, y: 0 }
    if (type === "*") return { x: 12, y: 0 }
    if (type === "/") return { x: 13, y: 0 }
    if (type === "=") return { x: 14, y: 0 }
    if (type === "<") return { x: 15, y: 0 }
    if (type === ">") return { x: 16, y: 0 }
    if (type === "%") return { x: 17, y: 0 }
    if (type === "pi") return { x: 18, y: 0 }
    if (type === "!") return { x: 19, y: 0 }
    if (type === "^") return { x: 20, y: 0 }
    if (type === "0small") return { x: 21, y: 0 }
    if (type === "1small") return { x: 22, y: 0 }
    if (type === "2small") return { x: 23, y: 0 }
    if (type === "3small") return { x: 24, y: 0 }
    if (type === "4small") return { x: 25, y: 0 }
    if (type === "5small") return { x: 26, y: 0 }
    if (type === "6small") return { x: 27, y: 0 }
    if (type === "7small") return { x: 28, y: 0 }
    if (type === "8small") return { x: 29, y: 0 }
    if (type === "9small") return { x: 30, y: 0 }
    if (type === "_") return { x: 31, y: 0 }
    // Row 1
    if (type === "aThick") return { x: 0, y: 1 }
    if (type === "bThick") return { x: 1, y: 1 }
    if (type === "cThick") return { x: 2, y: 1 }
    if (type === "dThick") return { x: 3, y: 1 }
    if (type === "eThick") return { x: 4, y: 1 }
    if (type === "fThick") return { x: 5, y: 1 }
    if (type === "gThick") return { x: 6, y: 1 }
    if (type === "hThick") return { x: 7, y: 1 }
    if (type === "iThick") return { x: 8, y: 1 }
    if (type === "jThick") return { x: 9, y: 1 }
    if (type === "kThick") return { x: 10, y: 1 }
    if (type === "lThick") return { x: 11, y: 1 }
    if (type === "mThick") return { x: 12, y: 1 }
    if (type === "nThick") return { x: 13, y: 1 }
    if (type === "oThick") return { x: 14, y: 1 }
    if (type === "pThick") return { x: 15, y: 1 }
    if (type === "qThick") return { x: 16, y: 1 }
    if (type === "rThick") return { x: 17, y: 1 }
    if (type === "sThick") return { x: 18, y: 1 }
    if (type === "tThick") return { x: 19, y: 1 }
    if (type === "uThick") return { x: 20, y: 1 }
    if (type === "vThick") return { x: 21, y: 1 }
    if (type === "wThick") return { x: 22, y: 1 }
    if (type === "xThick") return { x: 23, y: 1 }
    if (type === "yThick") return { x: 24, y: 1 }
    if (type === "zThick") return { x: 25, y: 1 }
    if (type === "solid") return { x: 26, y: 1 }
    if (type === "?") return { x: 27, y: 1 }
    if (type === "!") return { x: 28, y: 1 }
    if (type === "!!") return { x: 29, y: 1 }
    if (type === '"') return { x: 30, y: 1 }
    if (type === "_") return { x: 31, y: 1 }
    // Row 2
    if (type === "aFull") return { x: 0, y: 2 }
    if (type === "bFull") return { x: 1, y: 2 }
    if (type === "cFull") return { x: 2, y: 2 }
    if (type === "dFull") return { x: 3, y: 2 }
    if (type === "eFull") return { x: 4, y: 2 }
    if (type === "fFull") return { x: 5, y: 2 }
    if (type === "gFull") return { x: 6, y: 2 }
    if (type === "hFull") return { x: 7, y: 2 }
    if (type === "iFull") return { x: 8, y: 2 }
    if (type === "jFull") return { x: 9, y: 2 }
    if (type === "kFull") return { x: 10, y: 2 }
    if (type === "lFull") return { x: 11, y: 2 }
    if (type === "mFull") return { x: 12, y: 2 }
    if (type === "nFull") return { x: 13, y: 2 }
    if (type === "oFull") return { x: 14, y: 2 }
    if (type === "pFull") return { x: 15, y: 2 }
    if (type === "qFull") return { x: 16, y: 2 }
    if (type === "rFull") return { x: 17, y: 2 }
    if (type === "sFull") return { x: 18, y: 2 }
    if (type === "tFull") return { x: 19, y: 2 }
    if (type === "uFull") return { x: 20, y: 2 }
    if (type === "vFull") return { x: 21, y: 2 }
    if (type === "wFull") return { x: 22, y: 2 }
    if (type === "xFull") return { x: 23, y: 2 }
    if (type === "yFull") return { x: 24, y: 2 }
    if (type === "zFull") return { x: 25, y: 2 }
    if (type === "#") return { x: 26, y: 2 }
    // Row 3
    if (type === "aFancy") return { x: 0, y: 3 }
    if (type === "bFancy") return { x: 1, y: 3 }
    if (type === "cFancy") return { x: 2, y: 3 }
    if (type === "dFancy") return { x: 3, y: 3 }
    if (type === "eFancy") return { x: 4, y: 3 }
    if (type === "fFancy") return { x: 5, y: 3 }
    if (type === "gFancy") return { x: 6, y: 3 }
    if (type === "hFancy") return { x: 7, y: 3 }
    if (type === "iFancy") return { x: 8, y: 3 }
    if (type === "jFancy") return { x: 9, y: 3 }
    if (type === "kFancy") return { x: 10, y: 3 }
    if (type === "lFancy") return { x: 11, y: 3 }
    if (type === "mFancy") return { x: 12, y: 3 }
    if (type === "nFancy") return { x: 13, y: 3 }
    if (type === "oFancy") return { x: 14, y: 3 }
    if (type === "pFancy") return { x: 15, y: 3 }
    if (type === "qFancy") return { x: 16, y: 3 }
    if (type === "rFancy") return { x: 17, y: 3 }
    if (type === "sFancy") return { x: 18, y: 3 }
    if (type === "tFancy") return { x: 19, y: 3 }
    if (type === "uFancy") return { x: 20, y: 3 }
    if (type === "vFancy") return { x: 21, y: 3 }
    if (type === "wFancy") return { x: 22, y: 3 }
    if (type === "xFancy") return { x: 23, y: 3 }
    if (type === "yFancy") return { x: 24, y: 3 }
    if (type === "zFancy") return { x: 25, y: 3 }
    // Row 4
    if (type === "aLower") return { x: 0, y: 4 }
    if (type === "bLower") return { x: 1, y: 4 }
    if (type === "cLower") return { x: 2, y: 4 }
    if (type === "dLower") return { x: 3, y: 4 }
    if (type === "eLower") return { x: 4, y: 4 }
    if (type === "fLower") return { x: 5, y: 4 }
    if (type === "gLower") return { x: 6, y: 4 }
    if (type === "hLower") return { x: 7, y: 4 }
    if (type === "iLower") return { x: 8, y: 4 }
    if (type === "jLower") return { x: 9, y: 4 }
    if (type === "kLower") return { x: 10, y: 4 }
    if (type === "lLower") return { x: 11, y: 4 }
    if (type === "mLower") return { x: 12, y: 4 }
    if (type === "nLower") return { x: 13, y: 4 }
    if (type === "oLower") return { x: 14, y: 4 }
    if (type === "pLower") return { x: 15, y: 4 }
    if (type === "qLower") return { x: 16, y: 4 }
    if (type === "rLower") return { x: 17, y: 4 }
    if (type === "sLower") return { x: 18, y: 4 }
    if (type === "tLower") return { x: 19, y: 4 }
    if (type === "uLower") return { x: 20, y: 4 }
    if (type === "vLower") return { x: 21, y: 4 }
    if (type === "wLower") return { x: 22, y: 4 }
    if (type === "xLower") return { x: 23, y: 4 }
    if (type === "yLower") return { x: 24, y: 4 }
    if (type === "zLower") return { x: 25, y: 4 }
    // Row 5
    if (type === "aUpper") return { x: 0, y: 5 }
    if (type === "bUpper") return { x: 1, y: 5 }
    if (type === "cUpper") return { x: 2, y: 5 }
    if (type === "dUpper") return { x: 3, y: 5 }
    if (type === "eUpper") return { x: 4, y: 5 }
    if (type === "fUpper") return { x: 5, y: 5 }
    if (type === "gUpper") return { x: 6, y: 5 }
    if (type === "hUpper") return { x: 7, y: 5 }
    if (type === "iUpper") return { x: 8, y: 5 }
    if (type === "jUpper") return { x: 9, y: 5 }
    if (type === "kUpper") return { x: 10, y: 5 }
    if (type === "lUpper") return { x: 11, y: 5 }
    if (type === "mUpper") return { x: 12, y: 5 }
    if (type === "nUpper") return { x: 13, y: 5 }
    if (type === "oUpper") return { x: 14, y: 5 }
    if (type === "pUpper") return { x: 15, y: 5 }
    if (type === "qUpper") return { x: 16, y: 5 }
    if (type === "rUpper") return { x: 17, y: 5 }
    if (type === "sUpper") return { x: 18, y: 5 }
    if (type === "tUpper") return { x: 19, y: 5 }
    if (type === "uUpper") return { x: 20, y: 5 }
    if (type === "vUpper") return { x: 21, y: 5 }
    if (type === "wUpper") return { x: 22, y: 5 }
    if (type === "xUpper") return { x: 23, y: 5 }
    if (type === "yUpper") return { x: 24, y: 5 }
    if (type === "zUpper") return { x: 25, y: 5 }
    // Future Content
    if (type === "@") return { x: 15, y: 12 }
    if (type === "skull") return { x: 13, y: 6 }
    if (type === '.') return { x: 17, y: 14 }
    if (type === "shield") return { x: 19, y: 6 }
    if (type === "sword") return { x: 20, y: 6 }

}